/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Requested colors
        primary: '#0050cb',
        'primary-gradient-end': '#0066ff',
        surface: '#faf8ff',
        'surface-bright': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e0e4ff',
        'surface-container-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#44495a',
        'outline-variant': '#c4c8da',
        'primary-container': '#d8e2ff',
        'on-primary': '#ffffff',
        'secondary-container': '#dde1f9',
        'on-secondary-container': '#191c2c',
        'tertiary-fixed': '#d5f8e8',
        'on-tertiary-fixed-variant': '#0d5c34',
        'error-container': '#ffdad6',
        'on-error-container': '#410002',
        
        // Other support colors
        outline: '#737685',
        error: '#ba1a1a',
        background: '#faf8ff',
        'on-background': '#191b23',
        'inverse-surface': '#2e3038',
        'inverse-on-surface': '#f0f0fb',
        'inverse-primary': '#b3c5ff',
        'surface-tint': '#1155d0',
        'primary-fixed': '#dae1ff',
        'primary-fixed-dim': '#b3c5ff',
        'on-primary-fixed': '#001849',
        'on-primary-fixed-variant': '#003fa4',
        'secondary-fixed': '#dae1ff',
        'secondary-fixed-dim': '#b4c5fc',
        'on-secondary-fixed': '#031846',
        'on-secondary-fixed-variant': '#344574',
        'tertiary-fixed-dim': '#ffb59c',
        tertiary: '#7b2400',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#390c00',
        'surface-dim': '#d9d9e4',
        'surface-variant': '#e1e2ec',
      },
      fontFamily: {
        manrope: ['var(--font-manrope)', 'sans-serif'],
        inter: ['var(--font-inter)', 'sans-serif'],
      },
      borderRadius: {
        // Enforcing softer, rounder corners globally for a friendlier interface
        'none': '0px',
        'xs': '4px',
        'sm': '8px',
        'DEFAULT': '12px',
        'md': '14px',
        'lg': '16px',
        'xl': '20px',
        '2xl': '24px',
        '3xl': '32px',
        '4xl': '40px',
        'full': '9999px',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #0050cb, #0066ff)',
      },
      boxShadow: {
        ambient: '0 20px 40px rgba(19, 27, 46, 0.06)',
        soft: '0 12px 30px rgba(15, 23, 42, 0.08)',
        card: '0 2px 8px rgba(19, 27, 46, 0.04)',
      },
    },
  },
  plugins: [],
};
