module.exports = {
    content: [
        './src/app/**/*.{js,ts,jsx,tsx}',
        './src/components/**/*.{js,ts,jsx,tsx}',
        './src/lib/**/*.{js,ts,jsx,tsx}',
        './src/hooks/**/*.{js,ts,jsx,tsx}',
    ],
    theme: {
        extend: {
            colors: {
                brand: {
                    slate: '#0f172a',
                    slateLight: '#334155',
                    indigo: '#4338ca',
                    blue: '#3b82f6',
                    emerald: '#10b981',
                    rose: '#fb7185',
                    amber: '#f59e0b'
                },
                "primary-fixed": "#e2dfff",
                "error-container": "#ffdad6",
                "on-error": "#ffffff",
                "secondary-container": "#6cf8bb",
                "on-secondary-container": "#00714d",
                "tertiary-container": "#a44100",
                "surface-tint": "#4d44e3",
                "inverse-on-surface": "#eaf1ff",
                "primary-container": "#4f46e5",
                "surface-container-lowest": "#ffffff",
                "on-background": "#0b1c30",
                "inverse-surface": "#213145",
                "on-tertiary-fixed": "#351000",
                "tertiary-fixed": "#ffdbcc",
                "on-primary-fixed": "#0f0069",
                "tertiary": "#7e3000",
                "surface-bright": "#f8f9ff",
                "surface-dim": "#cbdbf5",
                "outline-variant": "#c7c4d8",
                "on-surface": "#0b1c30",
                "surface": "#f8f9ff",
                "on-error-container": "#93000a",
                "error": "#ba1a1a",
                "primary": "#3525cd",
                "background": "#f8f9ff",
                "tertiary-fixed-dim": "#ffb695",
                "on-surface-variant": "#464555",
                "on-secondary-fixed": "#002113",
                "surface-container": "#e5eeff",
                "outline": "#777587",
                "on-tertiary-container": "#ffd2be",
                "secondary-fixed-dim": "#4edea3",
                "on-secondary-fixed-variant": "#005236",
                "surface-container-high": "#dce9ff",
                "on-secondary": "#ffffff",
                "surface-container-low": "#eff4ff",
                "on-tertiary": "#ffffff",
                "secondary": "#006c49",
                "surface-container-highest": "#d3e4fe",
                "primary-fixed-dim": "#c3c0ff",
                "inverse-primary": "#c3c0ff",
                "secondary-fixed": "#6ffbbe",
                "on-primary-container": "#dad7ff",
                "on-primary": "#ffffff",
                "on-primary-fixed-variant": "#3323cc",
                "surface-variant": "#d3e4fe",
                "on-tertiary-fixed-variant": "#7b2f00"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "2xl": "1rem",
                "full": "9999px"
            },
            spacing: {
                "base": "4px",
                "sm": "8px",
                "container-max": "1280px",
                "margin-desktop": "32px",
                "gutter": "24px",
                "xs": "4px",
                "lg": "24px",
                "2xl": "48px",
                "3xl": "64px",
                "xl": "32px",
                "md": "16px",
                "margin-mobile": "16px"
            },
            fontFamily: {
                "body-sm": ["Inter"],
                "headline-md": ["Geist"],
                "label-md": ["Geist"],
                "body-md": ["Inter"],
                "title-md": ["Geist"],
                "title-lg": ["Geist"],
                "headline-lg": ["Geist"],
                "label-sm": ["Geist"],
                "headline-lg-mobile": ["Geist"],
                "display-lg": ["Geist"],
                "body-lg": ["Inter"]
            },
            fontSize: {
                "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "title-md": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
                "title-lg": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
                "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
            },
            boxShadow: {
                soft: '0 12px 30px rgba(15, 23, 42, 0.08)'
            }
        }
    },
    plugins: [],
};
