/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      xs: '475px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        // Semantic surface tokens — map to CSS variables
        surface:     'var(--color-surface)',
        'surface-low':     'var(--color-surface-low)',
        'surface-mid':     'var(--color-surface-mid)',
        'surface-high':    'var(--color-surface-high)',
        'surface-highest': 'var(--color-surface-highest)',
        'surface-bright':  'var(--color-surface-bright)',

        'on-surface': 'var(--color-on-surface)',
        'on-muted':   'var(--color-on-muted)',
        outline:      'var(--color-outline)',

        // Primary
        primary: {
          DEFAULT:   'var(--color-primary, #2e308a)',
          container: 'var(--color-primary-container)',
          foreground:'var(--color-on-primary)',
        },

        // Status
        'success-bg':   'var(--color-success-bg)',
        'success-text': 'var(--color-success-text)',
        'warn-bg':      'var(--color-warn-bg)',
        'warn-text':    'var(--color-warn-text)',
        'sticky-note':       'var(--color-sticky-note-bg)',
        'sticky-note-text':  'var(--color-sticky-note-text)',
        'sticky-note-muted': 'var(--color-sticky-note-muted)',
        'sticky-note-border':'var(--color-sticky-note-border)',
        'error-bg':     'var(--color-error-bg)',
        'error-text':   'var(--color-error-text)',

        // Preserve other support/original colors for compatibility
        'primary-end': '#4a4dc4',
        'primary-gradient-end': '#4a4dc4',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'outline-variant': 'var(--color-outline-variant)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary': 'var(--color-on-primary)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'error-container': 'var(--color-error-container)',
        'on-error-container': 'var(--color-on-error-container)',
        error: '#ba1a1a',
        background: '#faf8ff',
        'on-background': '#191b23',
        'inverse-surface': '#2e3038',
        'inverse-on-surface': '#f0f0fb',
        'inverse-primary': '#c0c1ff',
        'surface-tint': '#2e308a',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary-fixed': '#06016b',
        'on-primary-fixed-variant': '#393c95',
        'secondary-fixed': '#dae1ff',
        'secondary-fixed-dim': '#b4c5fc',
        'on-secondary-fixed': '#031846',
        'on-secondary-fixed-variant': '#344574',
        'tertiary-fixed-dim': '#ffb59c',
        tertiary: '#7b2400',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#390c00',
        'surface-dim': '#d9d9e4',
        'surface-variant': '#e1e2ec',
      },
      fontFamily: {
        manrope: ['var(--font-manrope)', 'sans-serif'],
        inter: ['var(--font-inter)', 'sans-serif'],
        mono: ['Space Mono', 'monospace'],
      },
      borderRadius: {
        // Enforcing softer, rounder corners globally for a friendlier interface
        'none': '0px',
        'xs': '4px',
        'sm': '8px',
        'DEFAULT': '12px',
        'md': '14px',
        'lg': '16px',
        'xl': '20px',
        '2xl': '24px',
        '3xl': '32px',
        '4xl': '40px',
        'full': '9999px',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #2e308a, #4a4dc4)',
      },
      boxShadow: {
        ambient: '0 20px 40px rgba(19, 27, 46, 0.06)',
        float: '0 32px 64px rgba(19, 27, 46, 0.12)',
        card: '0 8px 24px rgba(19, 27, 46, 0.05)',
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
