-- AlterTable
ALTER TABLE "User" ADD COLUMN "ai_studio_uses_month" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "report_exports_month" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "usage_month_reset_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
